# Generated by Django 4.1.7 on 2023-05-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(help_text='The name of quiz', max_length=50)),
                ('quiz_code', models.IntegerField(help_text='The code to join')),
                ('quiz_description', models.TextField()),
                ('quiz_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
