# Generated by Django 4.1.7 on 2023-05-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quizgo',
        ),
    ]
