# Generated by Django 4.1.7 on 2023-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_quiz_quizgo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgo',
            name='quiz_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
